import Head from 'next/head';
import { useState, useEffect } from 'react';
// @ts-ignore
import Header from '$Sections/Header/Header';
// @ts-ignore
import Nav from '$Sections/Nav/Nav';
// @ts-ignore
import Panel from '$Sections/Panel/Panel';
import { useRouter } from 'next/router';
// @ts-ignore
import Dash from '$Sections/Dash/Dash';
import styled from 'styled-components';
import create from 'zustand';
// import { supabase } from '../../../client.js';
import cookie from 'cookie';

interface Fire {
    count?: string;
    created_at?: string;
    id?: string;
    text?: string;
    text_title?: string;
    title?: string;
    topic?: string;
    url?: string;
}

// @ts-ignore
export default function Home({ fires }: Fire) {
    return (
        <UBMedia_App>
            <Head>
                <title >UBMOTF</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='HandheldFriendly' content='True'></meta>
                <meta name='viewport' content='width=device-width, initial-scale=1.0'></meta>
            </Head>

            <UBMedia_App_Shell_Parent>
                <UBMedia_App_Shell>
                    <Header></Header>
                    <UBMedia_App_Shell_Content>
                        <Nav></Nav>
                        <MainFlexContainer>
                            {/* @ts-ignore */}
                            <Dash fires={fires}></Dash>
                            <Panel></Panel>
                        </MainFlexContainer>
                    </UBMedia_App_Shell_Content>
                </UBMedia_App_Shell>
            </UBMedia_App_Shell_Parent>
        </UBMedia_App>
    );
}

const UBMedia_App = styled.div`
    border: 1.4px solid black;
    height: 100%;
    width: 100%;
    display: block;
`;

const UBMedia_App_Shell_Parent = styled.div`
    display: flex;
    height: 100%;
    width: 100%;
    background-color: #1a1b1c;
`;

const UBMedia_App_Shell = styled.div`
    display: flex;
    flex: 1 1 auto;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
    position: relative;
    width: 100%;
`;

const UBMedia_App_Shell_Content = styled.div`
    display: flex;
    flex: 1 1 auto;
    overflow: hidden;
    position: relative;
    border: 1.4px solid black;
`;

const MainFlexContainer = styled.main`
    display: flex;
    width: calc(100% - 166px);
    left: 166px;
    overflow: hidden;
    left: 166px;
    position: relative;
    border: 1.4px solid black;
    background-color: grey!important;
`;
