import type { NextPage } from 'next';
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '$styles/Home.module.css';
// REPorts
import Header from '$Sections/Header';
import Dash from 'src/#Sections^/Dash';
import Testy from '$Sections/Testy';
import Nav from '$Sections/Nav';
import Panel from '$Sections/Panel';
import Auth from 'src/@components^/Auth';
import styled from 'styled-components';
import { supabase } from '../../../client.js';
import { useRouter } from 'next/router';

// interface Fire {
//     count?: string;
//     created_at?: string;
//     id?: string;
//     text?: string;
//     text_title?: string;
//     title?: string;
//     topic?: string;
//     subtopic?: string;
//     subsubtopic?: string;
//     url?: string;
// }

export async function getServerSideProps() {
    let { data: fires, error } = await supabase.from('fires').select('*');

    if (!fires) {
        return {
            notFound: true,
        };
    }
    return {
        props: { fires }, // will be passed to the page component as props
    };
}

export default function Home({ fires }: any) {
    const [isLoading, setIsLoading] = useState(true);
    const [session, setSession] = useState<any>(null);
    const [session2, setSession2] = useState<any>(null);
    let apple = fires;
    console.log(fires);
    if (session2 && session2.length !== fires.length) {
        setSession2(apple);
    }
    const router = useRouter();

    return (
        <WebFire_App>
            <Head>
                <title>Richard Pitts FireNet</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='HandheldFriendly' content='True'></meta>
                <meta name='viewport' content='width=device-width, initial-scale=1.0'></meta>
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <WebFire_App_Shell_Parent>
                <WebFire_App_Shell>
                    <Header></Header>
                    <WebFire_App_Shell_Content>
                        <Nav></Nav>
                        <MainFlexContainer>
                            <Dash fires={fires}></Dash>
                            <Panel></Panel>
                        </MainFlexContainer>
                    </WebFire_App_Shell_Content>
                </WebFire_App_Shell>
            </WebFire_App_Shell_Parent>
        </WebFire_App>
    );
}

const WebFire_App = styled.div`
    border: 2px solid white;
    height: 100%;
    width: 100%;
    display: block;
`;

const WebFire_App_Shell_Parent = styled.div`
    display: flex;
    height: 100%;
    width: 100%;
    background-color: #1a1b1c;
`;

const WebFire_App_Shell = styled.div`
    display: flex;
    flex: 1 1 auto;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
    position: relative;
    width: 100%;
`;

const WebFire_App_Shell_Content = styled.div`
    display: flex;
    flex: 1 1 auto;
    overflow: hidden;
    position: relative;
    border: 2px solid white;
`;

const MainFlexContainer = styled.main`
    display: flex;
    /* flex: 1 1 auto; */
    width: calc(100% - 166px);
    left: 166px;
    overflow: hidden;
    left: 166px;
    position: relative;
    border: 4px solid yellow;
    border-top-left-radius: 12px;
`;
