import type { NextPage } from 'next'
import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '$styles/Home.module.css'
// REPorts
import Header from 'src/2_Sections/Header'
import Dash from 'src/2_Sections/Dash'
import Testy from 'src/2_Sections/Testy'
import Nav from 'src/2_Sections/Nav'
import Panel from 'src/2_Sections/Panel'
import styled from 'styled-components'

const WebFire_App = styled.div`
  border: 2px solid white;
  height: 100%;
  width: 100%;
  display: block;
`

const WebFire_App_Shell_Parent = styled.div`
  display: flex;
  height: 100%;
  width: 100%;
  background-color: #1a1b1c;
`

const WebFire_App_Shell = styled.div`
  display: flex;
  flex: 1 1 auto;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  position: relative;
  width: 100%;
`

const WebFire_App_Shell_Content = styled.div`
  display: flex;
  flex: 1 1 auto;
  overflow: hidden;
  position: relative;
  border: 2px solid white;
`

const MainFlexContainer = styled.main`
  display: flex;
  /* flex: 1 1 auto; */
  width: calc(100% - 166px);
  left: 166px;
  overflow: hidden;
  left: 166px;
  position: relative;
  border: 4px solid yellow;
  border-top-left-radius: 12px;
`

const Home: NextPage = () => {
  return (
    <WebFire_App>
      <Head>
        <title>Richard Pitts FireNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="HandheldFriendly" content="True"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WebFire_App_Shell_Parent>
        <WebFire_App_Shell>
          <Header></Header>
          <WebFire_App_Shell_Content>
            <Nav></Nav>
            <MainFlexContainer>
              <Dash></Dash>
              <Panel></Panel>
            </MainFlexContainer>
          </WebFire_App_Shell_Content>
        </WebFire_App_Shell>
      </WebFire_App_Shell_Parent>
    </WebFire_App>
  )
}

export default Home
