import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '$styles/Home.module.css'
// REPorts
import Header from '$Sections/Header'
import Dash from '$Sections/Dash'
import Testy from '$Sections/Testy'
import Nav from '$Sections/Nav'
import Panel from '$Sections/Panel'
import styled from 'styled-components'

const WebFire_App = styled.div`
  border: 2px solid white;
  height: 100%;
  width: 100%;
  display: block;
`

const WebFire_App_Shell_Parent = styled.div`
  display: flex;
  height: 100%;
  width: 100%;
  background-color: #1a1b1c;
`

const WebFire_App_Shell = styled.div`
  display: flex;
  flex: 1 1 auto;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  position: relative;
  width: 100%;
`

const MainFlexContainer = styled.main`
  display: flex;
  flex: 1 1 auto;
  overflow: hidden;
  width: 77%;
  top: 66px;
  border: 2px solid blue;
`

const Home: NextPage = () => {
  return (
    <WebFire_App>
      <Head>
        <title>webfire.me/Richard.Pitts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="HandheldFriendly" content="True"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WebFire_App_Shell_Parent>
        <WebFire_App_Shell>
          <Header></Header>

          <Nav></Nav>
          <MainFlexContainer>
            {/* <Dash></Dash> */}
            <Testy></Testy>
            <Panel></Panel>
          </MainFlexContainer>
        </WebFire_App_Shell>
      </WebFire_App_Shell_Parent>
    </WebFire_App>
  )
}

export default Home
